language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
  - "4.0"
  - "5.0"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
script: npm run-script test-cov
after_success:
  - test -e ./coverage/lcov.info && npm install codeclimate-test-reporter && codeclimate-test-reporter
    < ./coverage/lcov.info
notifications:
  email:
    - snowyu.lee@gmail.com
addons:
  code_climate:
    repo_token:
      secure: "UBHT+260DBou0zRqlvADldjym6/37NHalDvZ6ewQPy9xDjb17rU8y2tPXrC52Rg7Q4Zetom3jYXiHkFU/Z2ScRIfEB5WAgFn6yQs3Z5hg37niGwrouIWO3DR2vCi61KNJw0OPj98F6QUt1uzuzVCfGP6JjMsKLyT4fsBE8ju4jcObHVz7y1BJ4whH7CQj1rYuSoALksOGvp76GpgMhCTwK2VkLRHkl7bC0nh+4fBlX8FAfDjfXs8xRv4MR7ctdh8tv6fNVcvBRKKeAURCvEbIaH36DzOigkuGbHKBaoXxfDzj1Jfam3HIp087fr+6v4sUjxx/hFdsMGpwyNgTNUXWQB2E4OCjlZETusrMmEcOrQr4BnZ3PoQhXOVSB/i50MGiAyUQEyfGEYmPoBhMCfua9tgWLocCpfhOoZ49IxntoRSNm5mGnjzwIZDBcJsxmFk3JoHOM5CspBzx+W9WxUd2UkXTi/gTg6mieaA2dBFpQXzPQk4x8bYHp3ypqmpFN8ib2Dj7gN5Eh6q+P1KVSMltl//v3k6ab83WwDMnZkfSTnPHuINbjkgDc1LRssTTsOkzNsNTM2sD9ZF5nXyaDXabJcuwTqNjiubLYLoUwyqy8CMOAKnXL0sXWtHXCWLSGfpgKOyyd1NEjImXrbJFiCUNLAGU35q8/8zpzW3sc7GsuU="
